version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASS=new_password
      - DB_NAME=library

  db:
    image: mariadb:latest
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=new_password
      - MYSQL_DATABASE=library
    volumes:
      - dbdata:/var/lib/mysql
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql
      - ./dummy_data.sql:/docker-entrypoint-initdb.d/dummy_data.sql
volumes:
  dbdata:
